### ISSUE TITLE
Use of deprecated set-output command

### ISSUE THREAD

**Issue by anbonifacio** [colt-1/crate-version#1]
Hello,
when I run my actions that use crate-version on GitHub, they gives me this warning:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by colt-1** [comment]
must have missed this issue! #2 should have fixed this :D
